(()=>{
'use strict';
const q=new URLSearchParams(location.search);if(q.get('creator')!=='1')return;
const SB='https://pjskrjecyzoprpqhymbq.supabase.co',KEY='sb_publishable_PRyYNqhTAhk5sr3wKbIC0g_bYCLEhwd',FN=SB+'/functions/v1/sc-growth-support';
const $=(s,r=document)=>r.querySelector(s),esc=(x='')=>String(x).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let currentPid='';
const style=document.createElement('style');style.textContent=`
.sc-insights-btn{position:fixed;left:14px;bottom:18px;z-index:9500;border:0;background:#6f8c78;color:white;border-radius:999px;padding:12px 15px;font:900 13px/1 system-ui,-apple-system,"Segoe UI",sans-serif;box-shadow:0 12px 34px rgba(70,91,76,.2);cursor:pointer}.sc-insights-btn[hidden]{display:none!important}.sc-tools-modal{position:fixed;inset:0;z-index:12000;background:rgba(35,42,38,.42);display:grid;place-items:center;padding:18px}.sc-tools-card{width:min(900px,100%);max-height:90svh;overflow:auto;background:#fffdfa;border:1px solid #d9d7cf;border-radius:24px;padding:22px;box-shadow:0 22px 70px rgba(30,38,33,.24);color:#2f3b35}.sc-tools-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.sc-tools-card h2{font-family:Georgia,serif;font-size:34px;line-height:1;margin:7px 0 10px}.sc-tools-close{border:1px solid #d9d7cf;background:white;border-radius:12px;padding:9px 12px;font-weight:850;color:#5d6862;cursor:pointer}.sc-funnel{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px;margin:16px 0}.sc-fstat{background:#f4f7f3;border:1px solid #d9ded9;border-radius:15px;padding:12px}.sc-fstat small{display:block;color:#758078;font-size:10px;text-transform:uppercase;letter-spacing:.06em;font-weight:850}.sc-fstat strong{font-size:25px}.sc-drop{display:grid;gap:7px}.sc-drop-row{display:grid;grid-template-columns:80px 1fr 32px;gap:9px;align-items:center;font-size:12px}.sc-drop-track{height:9px;background:#eef1ed;border-radius:999px;overflow:hidden}.sc-drop-track span{display:block;height:100%;background:#c87559;border-radius:999px}.sc-private-note{margin-top:20px;border-top:1px solid #e0ddd5;padding-top:18px}.sc-private-note textarea{width:100%;min-height:86px;border:1px solid #d6ddd7;border-radius:14px;padding:12px;background:#fff;color:#34423a;resize:vertical}.sc-note-actions{display:flex;gap:8px;margin-top:9px}.sc-note-save{border:0;background:#6f8c78;color:white;border-radius:12px;padding:10px 13px;font-weight:850;cursor:pointer}.sc-note-list{display:grid;gap:8px;margin-top:12px}.sc-note{background:#f5f7f4;border:1px solid #dce1db;border-radius:13px;padding:11px}.sc-note p{margin:4px 0;white-space:pre-wrap}.sc-note small{color:#7a847d}.sc-note-del{border:0;background:none;color:#a85f49;text-decoration:underline;cursor:pointer;padding:3px 0}.sc-note-privacy{font-size:12px;color:#68736c;background:#eef3ee;border-radius:12px;padding:10px;margin:8px 0}.sc-tools-error{background:#f8e6df;color:#8d4935;padding:11px;border-radius:12px;margin-top:10px}
@media(max-width:680px){.sc-funnel{grid-template-columns:repeat(2,minmax(0,1fr))}.sc-insights-btn{left:10px;bottom:66px}.sc-tools-card{padding:18px}}
`;document.head.appendChild(style);
function token(){try{return sessionStorage.getItem('sc_creator_token')||''}catch{return''}}
function ready(){const app=$('#app');return !!token()&&!!app&&/YOUR PEOPLE|Creator/i.test(app.textContent||'')}
async function call(op,body={}){const t=token();if(!t)throw Error('Sign in to the Creator Dashboard again.');const r=await fetch(FN,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY,'Authorization':'Bearer '+t},body:JSON.stringify({op,...body})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Could not load creator tools.');return d}
function ensureButton(){let b=$('#scInsightsBtn');if(!b){b=document.createElement('button');b.id='scInsightsBtn';b.className='sc-insights-btn';b.textContent='↗ Insights';b.onclick=openInsights;document.body.appendChild(b)}b.hidden=!ready()}
function closeTools(){document.getElementById('scToolsModal')?.remove()}
async function openInsights(){
  closeTools();const m=document.createElement('div');m.id='scToolsModal';m.className='sc-tools-modal';m.innerHTML=`<section class="sc-tools-card"><div class="sc-tools-head"><div><div class="brand-kicker">SECOND CHANCE TESTER ANALYTICS</div><h2>Where people actually move.</h2></div><button class="sc-tools-close" id="scToolsClose">Close</button></div><p class="muted">This funnel is about behavior, not judgment. The point is to see where the program gets people moving — and where we lose them.</p><div id="scToolsBody"><p class="talk">Loading the funnel…</p></div></section>`;document.body.appendChild(m);$('#scToolsClose',m).onclick=closeTools;m.onclick=e=>{if(e.target===m)closeTools()};
  try{const d=await call('analytics'),c=d.counts||{},drops=d.dropoffs||[],max=Math.max(1,...drops.map(x=>+x.count||0));$('#scToolsBody',m).innerHTML=`<div class="sc-funnel">${[['Signups',c.signups],['Email confirmed',c.confirmed],['Onboarding',c.onboarding],['Step 1',c.step1],['Step 7',c.step7],['Step 21',c.step21],['Graduates',c.step51],['Active 7 days',c.active7]].map(x=>`<div class="sc-fstat"><small>${x[0]}</small><strong>${Number(x[1]||0)}</strong></div>`).join('')}</div><div class="panel" style="margin:0"><h3>Where unfinished journeys are sitting</h3>${drops.length?`<div class="sc-drop">${drops.map(x=>`<div class="sc-drop-row"><strong>Step ${x.step}</strong><div class="sc-drop-track"><span style="width:${Math.max(8,Math.round((x.count/max)*100))}%"></span></div><b>${x.count}</b></div>`).join('')}</div>`:'<p class="muted">Not enough tester activity yet.</p>'}<div class="coachline">Returns after a break: <strong>${Number(c.returns||0)}</strong>. In Second Chance, coming back counts as progress.</div></div>`}catch(e){$('#scToolsBody',m).innerHTML='<div class="sc-tools-error">'+esc(e.message)+'</div>'}
}

document.addEventListener('click',e=>{const row=e.target instanceof Element?e.target.closest('.person'):null;if(row?.dataset?.id)currentPid=row.dataset.id},true);
async function injectNotes(){
  if(!currentPid||!ready())return;const panel=$('#modal .panel');if(!panel||panel.querySelector('#scCreatorNotes'))return;
  const sec=document.createElement('div');sec.id='scCreatorNotes';sec.className='sc-private-note';sec.innerHTML=`<div class="tag">PRIVATE CREATOR NOTES</div><h3>Follow-up notes</h3><div class="sc-note-privacy">🔒 These notes are private to the creator side. They do not expose the participant’s private journal.</div><textarea id="scNoteText" maxlength="4000" placeholder="Example: Check back after Step 9 about confidence at work."></textarea><div class="sc-note-actions"><button class="sc-note-save" id="scNoteSave">Save private note</button></div><div id="scNoteMsg"></div><div class="sc-note-list" id="scNoteList"><span class="muted">Loading notes…</span></div>`;panel.appendChild(sec);$('#scNoteSave',sec).onclick=saveNote;await loadNotes();
}
async function loadNotes(){const list=$('#scNoteList');if(!list||!currentPid)return;try{const d=await call('notes',{participantId:currentPid}),notes=d.notes||[];list.innerHTML=notes.length?notes.map(n=>`<div class="sc-note" data-note="${n.id}"><small>${new Date(n.created_at).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</small><p>${esc(n.body)}</p><button class="sc-note-del" data-del="${n.id}">Delete</button></div>`).join(''):'<span class="muted">No private notes yet.</span>';list.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteNote(b.dataset.del))}catch(e){list.innerHTML='<div class="sc-tools-error">'+esc(e.message)+'</div>'}}
async function saveNote(){const box=$('#scNoteMsg'),ta=$('#scNoteText'),body=ta?.value.trim()||'';if(!body){box.innerHTML='<div class="sc-tools-error">Write a note first.</div>';return}try{await call('save_note',{participantId:currentPid,body});ta.value='';box.innerHTML='<div class="success">Private note saved.</div>';await loadNotes()}catch(e){box.innerHTML='<div class="sc-tools-error">'+esc(e.message)+'</div>'}}
async function deleteNote(id){try{await call('delete_note',{noteId:id});await loadNotes()}catch(e){const box=$('#scNoteMsg');if(box)box.innerHTML='<div class="sc-tools-error">'+esc(e.message)+'</div>'}}
const mo=new MutationObserver(()=>queueMicrotask(()=>{ensureButton();injectNotes()}));mo.observe(document.body,{childList:true,subtree:true});ensureButton();
})();