(()=>{
'use strict';
const SB='https://pjskrjecyzoprpqhymbq.supabase.co', KEY='sb_publishable_PRyYNqhTAhk5sr3wKbIC0g_bYCLEhwd', FN=SB+'/functions/v1/sc-growth-public';
const CATS=['health','money','career','relationships','discipline','confidence','home','purpose','peace'];
const LAB={health:'Health',money:'Money',career:'Work / Career',relationships:'Relationships',discipline:'Discipline',confidence:'Confidence',home:'Environment / Home',purpose:'Purpose',peace:'Peace'};
const S={access:'',refresh:'',user:null,p:null,d:null,step:1,sec:0,timers:{}};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=(x='')=>String(x).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const store={get(k){try{return localStorage.getItem(k)||''}catch{return''}},set(k,v){try{localStorage.setItem(k,String(v))}catch{}},del(k){try{localStorage.removeItem(k)}catch{}}};
function saveSession(a,r){S.access=a||'';S.refresh=r||'';if(a)store.set('sc_public_access',a);else store.del('sc_public_access');if(r)store.set('sc_public_refresh',r);else store.del('sc_public_refresh')}
S.access=store.get('sc_public_access');S.refresh=store.get('sc_public_refresh');
function view(html){$('#app').innerHTML=html;window.scrollTo(0,0)}
function toast(t){let n=$('#toast');if(!n)return;n.textContent=t;n.classList.add('show');clearTimeout(n._t);n._t=setTimeout(()=>n.classList.remove('show'),1300)}
function msg(el,text,ok=false){el.innerHTML='<div class="'+(ok?'public-success':'public-error')+'">'+esc(text)+'</div>'}
function authHeaders(){return{'Content-Type':'application/json','apikey':KEY,'Authorization':'Bearer '+S.access}}
async function authCall(path,body){const r=await fetch(SB+path,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY},body:JSON.stringify(body)});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.msg||d.error_description||d.message||d.error||'Could not finish that sign-in.');return d}
async function refreshToken(){if(!S.refresh)throw Error('Please sign in again.');const d=await authCall('/auth/v1/token?grant_type=refresh_token',{refresh_token:S.refresh});saveSession(d.access_token,d.refresh_token||S.refresh);S.user=d.user||S.user;return d}
async function api(op,body={}){if(!S.access)throw Error('Please sign in again.');let r=await fetch(FN,{method:'POST',headers:authHeaders(),body:JSON.stringify({op,...body})});if(r.status===401&&S.refresh){await refreshToken();r=await fetch(FN,{method:'POST',headers:authHeaders(),body:JSON.stringify({op,...body})})}let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||'Something went sideways.');return d}
function parseHash(){const h=new URLSearchParams(location.hash.replace(/^#/,'')),a=h.get('access_token'),r=h.get('refresh_token');if(a){saveSession(a,r||'');history.replaceState(null,'',location.pathname+location.search);return true}return false}
parseHash();
function headerUI(mode='Your journey'){return `<header class="top"><div><div class="brand-kicker">Second Chance</div><div class="brand">What if it all went right?</div></div><div class="mode">${esc(mode)}</div></header>`}
function nav(active='home'){return `<nav class="bottomnav"><button class="navbtn ${active==='home'?'active':''}" data-nav="home"><b>⌂</b>Journey</button><button class="navbtn ${active==='today'?'active':''}" data-nav="today"><b>→</b>Next move</button><button class="navbtn ${active==='receipts'?'active':''}" data-nav="receipts"><b>✓</b>Receipts</button></nav>`}
function bindNav(){$$('[data-nav]').forEach(b=>b.onclick=()=>b.dataset.nav==='home'?home():b.dataset.nav==='today'?openCurrent():receipts())}
const J=()=>S.d?.journey||{current_step:1,total_completed:0}, cur=()=>Math.min(Number(J().current_step||1),51), done=n=>!!S.d?.steps?.find(x=>+x.step_number===n&&x.status==='complete'), lev=n=>n<=7?'WAKE UP':n<=21?'LOCK IN':'BECOME';
const ref=(n,k)=>S.d?.reflections?.find(x=>+x.step_number===n&&x.prompt_key===k)?.body||'', dr=(n,k)=>S.d?.drafts?.find(x=>+x.step_number===n&&x.draft_key===k)?.body||'';
function cover(){const signed=!!S.access;view(`<main class="public-cover"><section class="cover-wrap"><h1 class="cover-brand">Second Chance</h1><p class="cover-sub">Journal. Reflect. Grow.</p><p class="cover-line">Your next chapter <em>starts here.</em></p><img class="cover-art" src="../second-chance-pilot/cover-art.svg" alt="What if your second chance changed everything?"><div class="cover-actions"><button class="cover-primary" id="start">${signed?'Continue My Second Chance':'Start My Second Chance'} &nbsp;→</button><button class="cover-secondary" id="access">I Already Have Access &nbsp;→</button></div><div class="cover-note">⌾ Your journey is private and secure.</div><button class="creator-link" id="creator">Creator access</button></section></main>`);$('#start').onclick=()=>signed?enter():signup();$('#access').onclick=login;$('#creator').onclick=()=>location.href='../second-chance-pilot/?creator=1'}
function authShell(title,sub,fields,primary){view(`<main class="auth-wrap"><section class="auth-card"><div class="auth-top"><div><div class="brand-kicker">Second Chance</div><h1>${esc(title)}</h1></div><button class="mini-back" id="back">Back</button></div><p class="muted">${esc(sub)}</p>${fields}<div class="auth-actions"><button class="btn-main" id="authGo">${esc(primary)}</button></div><div class="auth-msg" id="authMsg"></div></section></main>`);$('#back').onclick=cover}
function signup(){authShell('Start my second chance','Create your private account. Your email is only for access to your journey.',`<div class="field"><label>Email</label><input id="email" type="email" autocomplete="email"></div><div class="field"><label>Password</label><input id="pass" type="password" autocomplete="new-password" minlength="8"></div><div class="field"><label>Password again</label><input id="pass2" type="password" autocomplete="new-password" minlength="8"></div>`,`Create my account →`);$('#authGo').onclick=async()=>{const box=$('#authMsg'),email=$('#email').value.trim(),p=$('#pass').value,p2=$('#pass2').value;if(!email)return msg(box,'Put your email in first.');if(p.length<8)return msg(box,'Use at least 8 characters for your password.');if(p!==p2)return msg(box,'Those passwords do not match.');try{const d=await authCall('/auth/v1/signup',{email,password:p});if(d.access_token){saveSession(d.access_token,d.refresh_token);S.user=d.user;await enter()}else{msg(box,'Account created. Check your email to confirm it, then come back and tap “I Already Have Access.”',true)}}catch(e){msg(box,e.message)}}}
function login(){authShell('Welcome back','Use the email and password you made when you started.',`<div class="field"><label>Email</label><input id="email" type="email" autocomplete="email"></div><div class="field"><label>Password</label><input id="pass" type="password" autocomplete="current-password"></div>`,`Open my journey →`);$('#authGo').onclick=async()=>{const box=$('#authMsg'),email=$('#email').value.trim(),password=$('#pass').value;if(!email||!password)return msg(box,'Put in your email and password.');try{const d=await authCall('/auth/v1/token?grant_type=password',{email,password});saveSession(d.access_token,d.refresh_token);S.user=d.user;await enter()}catch(e){msg(box,e.message)}}}
async function enter(){try{const d=await api('bootstrap');if(d.needsSetup){setup();return}S.p=d.participant;S.d=d.state;home()}catch(e){if(/sign in/i.test(e.message)){logout();login()}else{authShell('Hold up','I could not open your journey.',`<div class="public-error">${esc(e.message)}</div>`,`Try again`);$('#authGo').onclick=enter}}}
function logout(){saveSession('','');S.user=S.p=S.d=null;cover()}
function setup(){let scores=Object.fromEntries(CATS.map(c=>[c,5]));view(`<main class="auth-wrap"><section class="auth-card"><div class="brand-kicker">Your starting point</div><h1>Make this yours.</h1><p class="muted">A few quick things, then we start. No streaks. No punishment. Your private writing stays private.</p><div class="field"><label>What should I call you?</label><input id="name" placeholder="First name or nickname"></div><div class="field"><label>How you want the push?</label><select id="pace" style="width:100%;padding:13px;border:1px solid #d6ddd7;border-radius:14px;background:white"><option value="my-own">My own pace</option><option value="steady">Steady</option><option value="push-me">Push me</option></select></div><h2>Where you at right now?</h2><p class="muted">1 means needs attention. 10 means feels strong. This ain't a grade.</p><div class="setup-grid">${CATS.map(c=>`<div class="setup-score"><div class="row"><span>${esc(LAB[c])}</span><output id="o_${c}">5</output></div><input class="startscore" data-cat="${c}" type="range" min="1" max="10" value="5"></div>`).join('')}</div><h2>Your three agreements</h2><label class="agreement"><input class="agree" type="checkbox"> <span>I do not have to do this perfectly.</span></label><label class="agreement"><input class="agree" type="checkbox"> <span>I will tell myself the truth.</span></label><label class="agreement"><input class="agree" type="checkbox"> <span>If I fall off, I am allowed to come back.</span></label><div class="auth-actions"><button class="btn-main" id="finish">Start Step 1 →</button><button class="btn-alt" id="out">Sign out</button></div><div id="setupMsg"></div></section></main>`);$$('.startscore').forEach(x=>x.oninput=()=>{scores[x.dataset.cat]=+x.value;$('#o_'+x.dataset.cat).textContent=x.value});$('#out').onclick=logout;$('#finish').onclick=async()=>{const name=$('#name').value.trim(),pace=$('#pace').value,all=$$('.agree').every(x=>x.checked);if(!name)return msg($('#setupMsg'),'Tell me what to call you.');if(!all)return msg($('#setupMsg'),'Check the three agreements first.');try{const d=await api('setup',{displayName:name,pace,scores});S.p=d.participant;S.d=d.state;home()}catch(e){msg($('#setupMsg'),e.message)}}}
function accountBar(){return `<div class="accountbar"><span>${esc(S.p?.display_name||'')}</span><button id="logout">Sign out</button></div>`}
function home(){const j=J(),d=+j.total_completed||0,p=Math.round(d/51*100),c=cur(),acts=S.d?.actions||[],moves=acts.filter(x=>x.status!=='not_yet').length,open=acts.filter(x=>x.status==='not_yet').length,n=S.p?.display_name||'cuz';view(`<div class="journey-shell">${accountBar()}${headerUI()}${nav('home')}<main class="homegrid"><section><div class="hero"><div class="eyebrow">Welcome back, ${esc(n)}</div><h1>${d>=51?'You finished.<br>Now live it.':'We still got<br>work to do.'}</h1><p>${d>=51?`51 completed steps. The program is complete. Your second chance ain't.`:`You ain't behind. You ain't late. You came back — that's enough.`}</p><div class="actions"><button class="btn" id="continue">${d>=51?'Open my Blueprint →':d===0?'Start Step 1 →':'Continue Step '+c+' →'}</button></div></div><div class="panel"><h2>Your journey</h2><p class="muted">${d} of 51 completed · ${p}%</p><div class="stepbar"><span style="width:${p}%"></span></div><div class="levels"><div class="level ${c<=7?'active':''}"><div class="level-num">01</div><strong>WAKE UP ${d>=7?'✓':''}</strong><small>7 steps · Get honest and choose a direction.</small></div><div class="level ${c>7&&c<=21?'active':''} ${d<7?'locked':''}"><div class="level-num">02</div><strong>LOCK IN ${d>=21?'✓':d<7?'🔒':''}</strong><small>14 steps · Turn insight into systems and action.</small></div><div class="level ${c>21?'active':''} ${d<21?'locked':''}"><div class="level-num">03</div><strong>BECOME ${d>=51?'✓':d<21?'🔒':''}</strong><small>30 steps · Build identity, standards, resilience, and a 90-day mission.</small></div></div></div></section><aside><div class="panel sidecard"><div class="tag">Your coach</div><h2>${d>=51?'You did that.':'Right here with you.'}</h2><p class="talk">${d>=51?`Nah. The program complete. Your second chance ain't. Now you gotta live this shit.`:d?`You already got ${d} receipt${d===1?'':'s'}. We just need the next one.`:`Come on, cuz. We just need one honest step.`}</p></div><div class="panel"><h2>Your receipts</h2><div class="stat-grid"><div class="stat"><small>Steps</small><strong>${d}</strong></div><div class="stat"><small>Moves</small><strong>${moves}</strong></div><div class="stat"><small>Open</small><strong>${open}</strong></div><div class="stat"><small>Level</small><strong style="font-size:19px">${lev(c)}</strong></div></div><div class="actions"><button class="btn secondary" id="receipts">Receipts</button><button class="btn ghost" id="feedback">Give feedback</button></div></div></aside></main></div>`);bindNav();$('#logout').onclick=logout;$('#continue').onclick=()=>d>=51?graduate():openCurrent();$('#receipts').onclick=receipts;$('#feedback').onclick=feedback}
async function openCurrent(){return openStep(cur(),0)}
async function openStep(n,sec=0){if(n>1&&!done(n-1))n=cur();S.step=n;S.sec=sec;try{await api('step_open',{stepNumber:n})}catch{}renderStep()}
function draftSave(n,key,val){clearTimeout(S.timers[key]);S.timers[key]=setTimeout(()=>api('save_draft',{stepNumber:n,draftKey:key,text:val}).catch(()=>{}),600)}
function scoreUI(vals,prefix){return `<div class="score-grid">${CATS.map(c=>`<div class="score"><div class="score-head"><span>${esc(LAB[c])}</span><output id="${prefix}o_${c}">${vals[c]}</output></div><input class="${prefix}score" data-cat="${c}" type="range" min="1" max="10" value="${vals[c]}"></div>`).join('')}</div>`}
function prevScores(cp){const order=cp==='after_wakeup'?'start':cp==='after_lockin'?'after_wakeup':'after_lockin';return Object.fromEntries(CATS.map(c=>[c,+S.d?.scores?.find(x=>x.checkpoint===order&&x.category===c)?.score||5]))}
function renderStep(){const x=STEPS[S.step-1],n=x.n,d=+J().total_completed||0,p=Math.round(d/51*100);let body='';if(S.sec===0)body=`<div class="tag">REAL TALK</div><p class="talk">${esc(x.talk)}</p><div class="moment"><strong>${esc(x.moment)}</strong>${esc(x.momentText)}</div><div class="coachline">We ain't judging the answer. We need the useful one.</div>`;
if(S.sec===1){body=`<div class="tag">CHECK YOURSELF</div><div class="field"><label>${esc(x.prompt)}</label><textarea id="r1">${esc(ref(n,'p1')||dr(n,'r1'))}</textarea></div><div class="field"><label>${esc(x.prompt2)}</label><textarea id="r2">${esc(ref(n,'p2')||dr(n,'r2'))}</textarea></div>${x.prompt3?`<div class="field"><label>${esc(x.prompt3)}</label><textarea id="r3">${esc(ref(n,'p3')||dr(n,'r3'))}</textarea></div>`:''}<div class="privacy">🔒 These answers are private by default.</div>`}
if(S.sec===2){body=`<div class="tag">MAKE A MOVE</div><h2>Pick one receipt for real life.</h2><div class="choice-grid">${x.actions.map((a,i)=>`<button class="choice move" data-v="${esc(a)}">${esc(a)}</button>`).join('')}</div><div class="field"><label>Or write your own move</label><input id="customMove" placeholder="One thing I will actually do"></div><h3>How'd it go?</h3><div class="chips"><button class="chip stat" data-s="done">Hell yeah — done</button><button class="chip stat" data-s="partly">Partly</button><button class="chip stat" data-s="not_yet">Not yet</button></div><div id="moveMsg"></div>`}
if(S.sec===3){const vals=x.score?prevScores(x.score):null;body=`<div class="tag">SHOW ME THE RECEIPTS</div><h2>${x.score?'Check yourself again.':'Close the loop.'}</h2>${x.score?`<p class="muted">Move the numbers only if they actually moved.</p>${scoreUI(vals,'end')}`:`<div class="statusbox">You showed up for Step ${n}. That counts. Finished is finished.</div>`}<div class="coachline">No streak. No reset. We just keep moving.</div>`}
view(`<div class="journey-shell">${headerUI(lev(n)+' · Step '+n)}<main class="stepwrap"><div class="progress"><span>${lev(n)} · ${n<=7?n+'/7':n<=21?(n-7)+'/14':(n-21)+'/30'}</span><span>${d}/51 complete</span></div><div class="stepbar"><span style="width:${p}%"></span></div><section class="panel"><div class="eyebrow">${esc(x.kicker)}</div><h1>${esc(x.title)}</h1>${body}<div class="actions"><button class="btn secondary" id="back">${S.sec===0?'Save & exit':'← Back'}</button><button class="btn" id="next">${S.sec===3?'Complete Step '+n+' ✓':'Continue →'}</button></div><div id="stepMsg"></div></section></main></div>`);
if(S.sec===1){['r1','r2','r3'].forEach(id=>{const el=$('#'+id);if(el)el.oninput=()=>draftSave(n,id,el.value)})}let chosen='',status='';if(S.sec===2){$$('.move').forEach(b=>b.onclick=()=>{$$('.move').forEach(x=>x.setAttribute('aria-pressed','false'));b.setAttribute('aria-pressed','true');chosen=b.dataset.v});$$('.stat').forEach(b=>b.onclick=()=>{$$('.stat').forEach(x=>x.setAttribute('aria-pressed','false'));b.setAttribute('aria-pressed','true');status=b.dataset.s})}if(S.sec===3&&x.score){const vals=prevScores(x.score);$$('.endscore').forEach(r=>r.oninput=()=>{vals[r.dataset.cat]=+r.value;$('#endo_'+r.dataset.cat).textContent=r.value});$('#next').onclick=async()=>{try{await api('save_scores',{checkpoint:x.score,scores:vals});await finishStep(x)}catch(e){msg($('#stepMsg'),e.message)}}}else $('#next').onclick=async()=>{if(S.sec===0){S.sec=1;return renderStep()}if(S.sec===1){const a=$('#r1').value.trim(),b=$('#r2').value.trim(),c=$('#r3')?.value.trim()||'';if(!a||!b)return msg($('#stepMsg'),'Give both questions a real answer first.');try{await api('save_reflection',{stepNumber:n,promptKey:'p1',text:a,isShared:false});await api('save_reflection',{stepNumber:n,promptKey:'p2',text:b,isShared:false});if(x.prompt3&&c)await api('save_reflection',{stepNumber:n,promptKey:'p3',text:c,isShared:false});S.sec=2;renderStep()}catch(e){msg($('#stepMsg'),e.message)}return}if(S.sec===2){const custom=$('#customMove').value.trim(),action=custom||chosen;if(!action)return msg($('#moveMsg'),'Pick or write one move.');if(!status)return msg($('#moveMsg'),'Tell me how it went.');try{await api('save_action',{stepNumber:n,actionType:custom?'custom':'suggested',actionLabel:action,status});S.sec=3;renderStep()}catch(e){msg($('#moveMsg'),e.message)}return}if(S.sec===3)finishStep(x)};
$('#back').onclick=()=>S.sec===0?home():(S.sec--,renderStep())}
async function finishStep(x){try{const d=await api('complete_step',{stepNumber:x.n});S.d=d.state||S.d;if(x.reward){reward(x);return}toast('Step '+x.n+' handled ✓');if(x.n>=51)graduate();else home()}catch(e){msg($('#stepMsg'),e.message)}}
function reward(x){const total=+J().total_completed||x.n;view(`${headerUI('Level complete')}<main class="stepwrap"><section class="hero"><div class="eyebrow">${lev(x.n)} COMPLETE</div><h1>${x.n===7?'You woke some shit up.':x.n===21?'Now it is locked in.':'You became somebody on purpose.'}</h1><p>${x.n===7?'Seven completed steps. You got honest, named what matters, and made real moves.':x.n===21?'Twenty-one completed steps. Insight got systems behind it now.':'Fifty-one completed steps. You did not need perfection. You finished.'}</p></section><section class="panel"><div class="tag">UNLOCKED</div><h2>${esc(x.reward)}</h2><p class="talk">${x.n===7?'Your Second Chance Statement is your direction in your own words.':x.n===21?'Your Progress Report is proof that the person doing the work is different from the person who started.':'Your Blueprint is what you take with you from here.'}</p><div class="actions"><button class="btn" id="go">${x.n===51?'Open my Blueprint →':'Keep going →'}</button></div></section></main>`);$('#go').onclick=()=>x.n===51?graduate():home()}
function receipts(){const d=+J().total_completed||0,a=S.d?.actions||[],scores=S.d?.scores||[];view(`<div class="journey-shell">${accountBar()}${headerUI('Your receipts')}${nav('receipts')}<main class="stepwrap"><section class="hero"><div class="eyebrow">PROOF, NOT STREAKS</div><h1>You been<br>putting in work.</h1><p>Finished work does not disappear because life got busy.</p></section><section class="panel"><div class="stat-grid"><div class="stat"><small>Steps finished</small><strong>${d}</strong></div><div class="stat"><small>Moves done</small><strong>${a.filter(x=>x.status==='done').length}</strong></div><div class="stat"><small>Partly</small><strong>${a.filter(x=>x.status==='partly').length}</strong></div><div class="stat"><small>Not yet</small><strong>${a.filter(x=>x.status==='not_yet').length}</strong></div></div><h2>Recent moves</h2>${a.length?a.slice(-8).reverse().map(x=>`<div class="statusbox"><strong>Step ${x.step_number}</strong> · ${esc(x.status.replace('_',' '))}<br>${esc(x.action_label)}</div>`).join(''):'<p class="muted">Your action receipts will show here.</p>'}<h2>Life Score checkpoints</h2>${['start','after_wakeup','after_lockin','final'].map(cp=>{const rows=scores.filter(x=>x.checkpoint===cp);return rows.length?`<div class="statusbox"><strong>${esc(cp.replaceAll('_',' '))}</strong><br>${rows.map(r=>esc(LAB[r.category])+': '+r.score).join(' · ')}</div>`:''}).join('')}</section></main></div>`);bindNav();$('#logout').onclick=logout}
function feedback(){view(`${headerUI('Feedback you choose to share')}<main class="stepwrap"><section class="panel"><div class="tag">SHARED WITH CREATOR</div><h1>Tell me if this shit actually works.</h1><p class="muted">This is not your private journal. Anything you put on this screen is feedback you are intentionally sending to the creator.</p><h3>How is the experience?</h3><div class="chips">${[1,2,3,4,5].map(n=>`<button class="chip rate" data-r="${n}">${n}${n===5?' 🔥':''}</button>`).join('')}</div><div class="field"><label>What hit?</label><textarea id="hit"></textarea></div><div class="field"><label>What felt off or confusing?</label><textarea id="off"></textarea></div><div class="field"><label>What would make it better?</label><textarea id="chg"></textarea></div><div class="actions"><button class="btn secondary" id="cancel">Back</button><button class="btn" id="send">Send feedback</button></div><div id="fmsg"></div></section></main>`);let rating=0;$$('.rate').forEach(b=>b.onclick=()=>{rating=+b.dataset.r;$$('.rate').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))});$('#cancel').onclick=home;$('#send').onclick=async()=>{const hit=$('#hit').value.trim(),off=$('#off').value.trim(),chg=$('#chg').value.trim();if(!rating)return msg($('#fmsg'),'Give it a 1–5 first.');if(!hit&&!off&&!chg)return msg($('#fmsg'),'Give me at least one thought.');try{await api('save_feedback',{checkpoint:+J().total_completed>=51?'final':+J().total_completed>=21?'after_lockin':+J().total_completed>=7?'after_wakeup':'general',rating,whatHit:hit,whatFeltOff:off,changeRequest:chg});msg($('#fmsg'),'Got it. Appreciate you keeping it real.',true)}catch(e){msg($('#fmsg'),e.message)}}}
function graduate(){const s=S.d?.scores||[],start=Object.fromEntries(s.filter(x=>x.checkpoint==='start').map(x=>[x.category,x.score])),final=Object.fromEntries(s.filter(x=>x.checkpoint==='final').map(x=>[x.category,x.score]));let best=null;CATS.forEach(c=>{if(start[c]!=null&&final[c]!=null){const diff=final[c]-start[c];if(!best||diff>best.diff)best={c,diff}}});const mission=ref(51,'p3')||ref(51,'p1')||'Live the standards you spent 51 steps building.';view(`${headerUI('Second Chance Graduate')}<main class="stepwrap"><section class="hero"><div class="eyebrow">51 / 51 COMPLETE</div><h1>Man… you actually<br>got your shit together.</h1><p>Not because everything is perfect. Because you learned how to tell yourself the truth, make a move, fall off, come back, and finish.</p></section><section class="panel"><div class="tag">YOUR SECOND CHANCE BLUEPRINT</div><h2>90-day mission</h2><p class="talk">${esc(mission)}</p>${best?`<div class="statusbox"><strong>Biggest Life Score movement:</strong> ${esc(LAB[best.c])} ${best.diff>=0?'+':''}${best.diff}</div>`:''}<h2>Protect these</h2><div class="statusbox">1. Your weekly reset.<br>2. The standards that made you trust yourself again.<br>3. The habit of coming back instead of starting over.</div><h2>Stop feeding these</h2><div class="statusbox">1. Avoidance dressed up as waiting.<br>2. All-or-nothing thinking.<br>3. The version of you that needs perfect conditions.</div><div class="coachline">Nah. The program complete. Your second chance ain't. Now you gotta live this shit.</div><div class="actions"><button class="btn secondary" id="home">Back to my journey</button></div></section></main>`);$('#home').onclick=home}
cover();
})();