(()=>{
'use strict';
const SB='https://pjskrjecyzoprpqhymbq.supabase.co',KEY='sb_publishable_PRyYNqhTAhk5sr3wKbIC0g_bYCLEhwd',FN=SB+'/functions/v1/sc-growth-chat';
const root=document.getElementById('chatRoot'),q=new URLSearchParams(location.search),creator=q.get('creator')==='1';
const esc=(x='')=>String(x).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=x=>{try{return new Date(x).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}catch{return''}};
const get=(k,session=false)=>{try{return (session?sessionStorage:localStorage).getItem(k)||''}catch{return''}};
const set=(k,v,session=false)=>{try{(session?sessionStorage:localStorage).setItem(k,String(v))}catch{}};
let selected='',timer=null,lastCount=-1,nearBottom=true,lastInboxUnread=null;
function token(){return creator?get('sc_creator_token',true):get('sc_public_access')}
function refreshToken(){return creator?get('sc_creator_refresh',true):get('sc_public_refresh')}
function saveTokens(a,r){if(creator){if(a)set('sc_creator_token',a,true);if(r)set('sc_creator_refresh',r,true)}else{if(a)set('sc_public_access',a);if(r)set('sc_public_refresh',r)}}
async function auth(path,body){const r=await fetch(SB+path,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY},body:JSON.stringify(body)});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error_description||d.msg||d.message||d.error||'Could not sign in.');return d}
async function refresh(){const r=refreshToken();if(!r)throw Error('Please sign in again.');const d=await auth('/auth/v1/token?grant_type=refresh_token',{refresh_token:r});saveTokens(d.access_token,d.refresh_token||r);return d.access_token}
async function call(op,body={}){let t=token();if(!t)throw Error('Please sign in again.');let r=await fetch(FN,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY,'Authorization':'Bearer '+t},body:JSON.stringify({op,...body})});if(r.status===401&&refreshToken()){t=await refresh();r=await fetch(FN,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY,'Authorization':'Bearer '+t},body:JSON.stringify({op,...body})})}let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||'Chat hit a snag.');return d}
function clearPoll(){if(timer)clearInterval(timer);timer=null}
function back(){location.href=creator?'../second-chance-pilot/?creator=1':'./'}
function header(name,sub,backLabel='Back'){return `<header class="chat-head"><div class="head-row"><button class="back" id="back">← ${esc(backLabel)}</button><div class="who"><strong>${esc(name)}</strong><small><span class="status-dot"></span>${esc(sub)}</small></div><div style="width:66px"></div></div><div class="eta">Message anytime · I’ll get back to you within <strong>8–12 hours.</strong></div></header>`}
function bubble(m,me){const cx=m.context_step?`<div class="context">From Step ${m.context_step}${m.context_section?' · '+esc(m.context_section):''}</div>`:'';return `<div class="msg ${me?'me':'them'}"><div class="bubble">${cx}${esc(m.body)}<div class="meta">${fmt(m.created_at)}${me&&m.read_at?' · Read':''}</div></div></div>`}
function composer(){return `<footer class="composer"><div class="compose-row"><textarea id="message" rows="1" maxlength="4000" placeholder="Type your message…"></textarea><button class="send" id="send" aria-label="Send message">↑</button></div><div class="send-note">Chat is separate from your private journal. Only what you send here is shared with Marquise.</div></footer>`}
function bindComposer(sendFn){const box=document.getElementById('message'),btn=document.getElementById('send');if(!box||!btn)return;const resize=()=>{box.style.height='auto';box.style.height=Math.min(box.scrollHeight,130)+'px'};box.oninput=resize;box.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendFn()}};btn.onclick=sendFn}
function alertsOn(){return get('sc_creator_message_alerts')==='1'&&'Notification'in window&&Notification.permission==='granted'}
async function enableAlerts(){if(!('Notification'in window)){alert('This browser does not support message notifications.');return}const p=await Notification.requestPermission();set('sc_creator_message_alerts',p==='granted'?'1':'0');const b=document.getElementById('alerts');if(b)b.textContent=p==='granted'?'🔔 Message alerts on':'🔕 Enable message alerts'}
function notifyUnread(n){if(!alertsOn()||!n)return;try{new Notification('New Second Chance message',{body:n===1?'You have 1 unread participant message.':`You have ${n} unread participant messages.`,icon:'../second-chance-pilot/icon.svg'})}catch{}}
async function participantStart(){if(!token()){root.innerHTML=`<main class="auth"><section class="auth-card"><div class="brand-kicker">Second Chance</div><h1>Sign in first.</h1><p>This chat belongs to your private Second Chance account.</p><button class="primary" id="go">Open Second Chance →</button></section></main>`;document.getElementById('go').onclick=()=>location.href='./';return}await participantThread(true);clearPoll();timer=setInterval(()=>{if(document.visibilityState==='visible')participantThread(false).catch(()=>{})},3000)}
async function participantThread(first=false){const d=await call('thread');const msgs=d.messages||[],p=d.participant||{};if(first||root.dataset.mode!=='participant'){root.dataset.mode='participant';root.innerHTML=`<div class="chat-app">${header('Marquise','Second Chance Creator','Journey')}<main class="chat-main"><section class="welcome"><div class="k">Wanna talk through it?</div><h1>What’s up? Talk to me.</h1><p>You can message me whenever you need to work something out, get unstuck, or just say where you’re at.</p><div class="privacy">🔒 Your journal stays private. This conversation is the only thing you’re choosing to share here.</div><div class="crisis"><strong>Not emergency support.</strong> If you’re in immediate danger, contact local emergency services. In the U.S., call or text <strong>988</strong> for the Suicide & Crisis Lifeline.</div></section><div class="messages" id="messages"></div></main>${composer()}</div>`;document.getElementById('back').onclick=back;bindComposer(sendParticipant)}const list=document.getElementById('messages');if(!list)return;const shouldScroll=first||nearBottom||msgs.length!==lastCount;list.innerHTML=msgs.length?msgs.map(m=>bubble(m,m.sender_type==='participant')).join(''):`<div class="empty">No messages yet. Send the first one when you’re ready.</div>`;lastCount=msgs.length;if(shouldScroll)setTimeout(()=>window.scrollTo(0,document.body.scrollHeight),30);nearBottom=(window.innerHeight+window.scrollY)>=document.body.scrollHeight-160}
async function sendParticipant(){const box=document.getElementById('message'),btn=document.getElementById('send'),body=box?.value.trim()||'';if(!body)return;btn.disabled=true;const step=Number(get('sc_chat_context_step')),section=get('sc_chat_context_section');try{await call('send',{body,stepNumber:Number.isInteger(step)&&step>0?step:null,section:section||null});box.value='';box.style.height='auto';await participantThread(false)}catch(e){alert(e.message)}finally{btn.disabled=false;box.focus()}}
function creatorLogin(){clearPoll();root.innerHTML=`<main class="auth"><section class="auth-card"><div class="brand-kicker">Second Chance</div><h1>Creator messages</h1><p>Sign in with your creator account.</p><div class="field"><label>Email</label><input id="email" type="email" autocomplete="email"></div><div class="field"><label>Password</label><input id="pass" type="password" autocomplete="current-password"></div><button class="primary" id="in">Sign in →</button><button class="back" id="dash" style="width:100%;margin-top:10px">Back to dashboard</button><div id="msg"></div></section></main>`;document.getElementById('dash').onclick=back;document.getElementById('in').onclick=async()=>{const box=document.getElementById('msg');try{const d=await auth('/auth/v1/token?grant_type=password',{email:document.getElementById('email').value.trim(),password:document.getElementById('pass').value});saveTokens(d.access_token,d.refresh_token||'');creatorInbox(true)}catch(e){box.innerHTML='<div class="error">'+esc(e.message)+'</div>'}}}
async function creatorStart(){if(!token())return creatorLogin();try{await creatorInbox(true)}catch(e){if(/sign in/i.test(e.message))creatorLogin();else root.innerHTML='<div class="error">'+esc(e.message)+'</div>'}}
async function creatorInbox(first=false){selected='';clearPoll();const d=await call('inbox'),threads=d.threads||[],unread=threads.reduce((a,x)=>a+(+x.unread||0),0);lastInboxUnread=unread;document.title=(unread?'('+unread+') ':'')+'Second Chance Messages';root.dataset.mode='creatorInbox';root.innerHTML=`<div>${header('Second Chance Messages','Creator inbox','Dashboard')}<main class="inbox-shell"><div class="k" style="font-size:11px;letter-spacing:.12em;text-transform:uppercase;font-weight:900;color:#c87559">YOUR PEOPLE</div><h1 class="admin-title">Talk it through.</h1><p class="admin-sub">Participants can message anytime. They’re told you’ll reply within 8–12 hours, so there’s no expectation that you’re sitting here all day.</p><div class="admin-actions"><button class="alert-toggle" id="alerts">${alertsOn()?'🔔 Message alerts on':'🔕 Enable message alerts'}</button></div><div class="thread-list">${threads.length?threads.map(x=>{const p=x.participant||{},j=x.journey||{},m=x.lastMessage||{};return `<button class="thread" data-id="${p.id}"><div><strong>${esc(p.display_name||'Participant')}</strong><span class="progress-pill">${+j.total_completed||0}/51 · Step ${+j.current_step||1}</span><p>${m.sender_type==='creator'?'You: ':''}${esc(m.body||'')}</p><small>${fmt(m.created_at)}</small></div>${x.unread?`<span class="unread">${x.unread}</span>`:''}</button>`}).join(''):`<div class="empty">No conversations yet. When somebody taps “Wanna talk through it?” and messages you, they’ll show up here.</div>`}</div></main></div>`;document.getElementById('back').onclick=back;document.getElementById('alerts').onclick=enableAlerts;document.querySelectorAll('.thread').forEach(b=>b.onclick=()=>creatorThread(b.dataset.id,true));timer=setInterval(()=>{if(document.visibilityState==='visible'&&root.dataset.mode==='creatorInbox')refreshInboxQuiet().catch(()=>{})},5000)}
async function refreshInboxQuiet(){const d=await call('inbox'),threads=d.threads||[],unread=threads.reduce((a,x)=>a+(+x.unread||0),0);if(lastInboxUnread!==null&&unread>lastInboxUnread)notifyUnread(unread);lastInboxUnread=unread;document.title=(unread?'('+unread+') ':'')+'Second Chance Messages';const old=document.querySelector('.thread-list');if(!old)return;old.innerHTML=threads.length?threads.map(x=>{const p=x.participant||{},j=x.journey||{},m=x.lastMessage||{};return `<button class="thread" data-id="${p.id}"><div><strong>${esc(p.display_name||'Participant')}</strong><span class="progress-pill">${+j.total_completed||0}/51 · Step ${+j.current_step||1}</span><p>${m.sender_type==='creator'?'You: ':''}${esc(m.body||'')}</p><small>${fmt(m.created_at)}</small></div>${x.unread?`<span class="unread">${x.unread}</span>`:''}</button>`}).join(''):`<div class="empty">No conversations yet.</div>`;old.querySelectorAll('.thread').forEach(b=>b.onclick=()=>creatorThread(b.dataset.id,true))}
function quickReplies(){const a=[`I got you — give me a few hours.`,`Tell me a little more.`,`What step are you stuck on?`,`You ain't behind. Pick up where you left off.`];return `<div class="quick-replies"><small>QUICK REPLIES</small>${a.map((x,i)=>`<button class="quick" data-q="${i}">${esc(x)}</button>`).join('')}</div>`}
async function sendQuick(text){if(!selected||!text)return;try{await call('send',{participantId:selected,body:text});await creatorThread(selected,false)}catch(e){alert(e.message)}}
async function creatorThread(pid,first=false){selected=pid;clearPoll();const d=await call('thread',{participantId:pid}),msgs=d.messages||[],p=d.participant||{},j=d.journey||{};document.title=(p.display_name||'Participant')+' · Second Chance';if(first||root.dataset.mode!=='creatorThread'||root.dataset.pid!==pid){root.dataset.mode='creatorThread';root.dataset.pid=pid;root.innerHTML=`<div class="chat-app creator-chat">${header(p.display_name||'Participant',`${+j.total_completed||0}/51 completed · Step ${+j.current_step||1}`,'Inbox')}<main class="chat-main"><section class="welcome"><div class="k">DIRECT CONVERSATION</div><h1>${esc(p.display_name||'Participant')}</h1><p>Only messages they intentionally send here are visible. Their private journal stays private.</p></section>${quickReplies()}<div class="messages" id="messages"></div></main>${composer()}</div>`;document.getElementById('back').onclick=()=>creatorInbox(true);bindComposer(sendCreator);const replies=[`I got you — give me a few hours.`,`Tell me a little more.`,`What step are you stuck on?`,`You ain't behind. Pick up where you left off.`];document.querySelectorAll('.quick').forEach(b=>b.onclick=()=>sendQuick(replies[+b.dataset.q]))}const list=document.getElementById('messages');if(list){list.innerHTML=msgs.length?msgs.map(m=>bubble(m,m.sender_type==='creator')).join(''):`<div class="empty">No messages yet.</div>`;if(first||msgs.length!==lastCount)setTimeout(()=>window.scrollTo(0,document.body.scrollHeight),30);lastCount=msgs.length}timer=setInterval(()=>{if(document.visibilityState==='visible'&&selected===pid)creatorThread(pid,false).catch(()=>{})},3000)}
async function sendCreator(){const box=document.getElementById('message'),btn=document.getElementById('send'),body=box?.value.trim()||'';if(!body||!selected)return;btn.disabled=true;try{await call('send',{participantId:selected,body});box.value='';box.style.height='auto';await creatorThread(selected,false)}catch(e){alert(e.message)}finally{btn.disabled=false;box.focus()}}
window.addEventListener('beforeunload',clearPoll);creator?creatorStart():participantStart();
})();